# FROM mysql:latest

# ENV MYSQL_ROOT_PASSWORD=root

# COPY ./init.sql /docker-entrypoint-initdb.d/

FROM node:20-alpine3.19

ADD ./scripts/init.sql /docker-entrypoint-initdb.d/

ENTRYPOINT ["docker-entrypoint.sh"]

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV PORT=8081

EXPOSE 8081

CMD [ "npm", "run", "dev" ]

